services:
  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    depends_on:
      - php
      - mysql
  php:
    build:
      context: images/php
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/public_html
    depends_on:
      - mysql
  mysql:
    image: 'mysql:9.0'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '1500:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql